"""
Admin endpoints — seed data, reset, diagnostics.
Protected by ADMIN_SECRET header. Only enabled when ENABLE_ADMIN=true.
"""
import os
from fastapi import APIRouter, Header, HTTPException
from services import firestore_service

router = APIRouter(prefix="/admin", tags=["admin"])

# Pre-computed seed submissions — insights already extracted, no Gemini call needed
SEED_DATA = [
    {"original_text": "The road from Pedanandipadu to taluk hospital is broken for 3 km. Ambulances cannot pass and two patients died last month. Over 400 families are affected.", "translated_text": "The road from Pedanandipadu to taluk hospital is broken for 3 km. Ambulances cannot pass and two patients died last month. Over 400 families are affected.", "source_language": "en", "constituency": "Demo Constituency", "district": "", "lat": 16.2601, "lng": 80.1453, "input_type": "text", "theme": "Roads & Infrastructure", "summary": "Road broken 3km, ambulances can't pass, 400 families affected", "urgency": "High", "sentiment": "Negative", "keywords": ["road", "hospital", "ambulance", "families"], "location_hint": "Pedanandipadu to taluk hospital", "demand_count_hint": "400 families"},
    {"original_text": "हमारे गाँव की सड़क बहुत खराब है। बरसात में बच्चे स्कूल नहीं जा पाते। 6 महीने से कोई मरम्मत नहीं हुई। 250 परिवार प्रभावित हैं।", "translated_text": "The road in our village is very bad. Children cannot go to school in the rain. No repair has been done for 6 months. 250 families are affected.", "source_language": "hi", "constituency": "Demo Constituency", "district": "", "lat": 16.2134, "lng": 80.0876, "input_type": "text", "theme": "Roads & Infrastructure", "summary": "Village road unrepaired 6 months, 250 families, children missing school", "urgency": "High", "sentiment": "Negative", "keywords": ["road", "school", "repair", "families"], "location_hint": "village road", "demand_count_hint": "250 families"},
    {"original_text": "Bridge over Nagarjuna canal near Vinukonda collapsed partially 2 months ago. School buses are taking a 15 km detour. Urgently needs repair.", "translated_text": "Bridge over Nagarjuna canal near Vinukonda collapsed partially 2 months ago. School buses are taking a 15 km detour. Urgently needs repair.", "source_language": "en", "constituency": "Demo Constituency", "district": "", "lat": 16.1823, "lng": 79.8934, "input_type": "text", "theme": "Roads & Infrastructure", "summary": "Bridge collapsed 2 months ago, school buses on 15km detour", "urgency": "High", "sentiment": "Negative", "keywords": ["bridge", "canal", "school", "detour"], "location_hint": "Vinukonda Nagarjuna canal", "demand_count_hint": "school children"},
    {"original_text": "Street lights on main road from Chilakaluripet to Sattenapalli are non-functional for 8 months. Night accidents have increased. Women feel unsafe walking after 7 PM.", "translated_text": "Street lights on main road from Chilakaluripet to Sattenapalli are non-functional for 8 months. Night accidents have increased. Women feel unsafe walking after 7 PM.", "source_language": "en", "constituency": "Demo Constituency", "district": "", "lat": 16.2987, "lng": 80.1678, "input_type": "text", "theme": "Roads & Infrastructure", "summary": "Street lights broken 8 months, night accidents up, women unsafe", "urgency": "High", "sentiment": "Negative", "keywords": ["street lights", "accidents", "women safety"], "location_hint": "Chilakaluripet to Sattenapalli", "demand_count_hint": "road users"},
    {"original_text": "Drainage overflows onto the main road during every rain, making it impassable. The drainage system was built in 1986 and never upgraded.", "translated_text": "Drainage overflows onto the main road during every rain, making it impassable. The drainage system was built in 1986 and never upgraded.", "source_language": "en", "constituency": "Demo Constituency", "district": "", "lat": 16.2245, "lng": 80.1123, "input_type": "text", "theme": "Roads & Infrastructure", "summary": "1986 drainage system overflows every rain, road impassable", "urgency": "Medium", "sentiment": "Negative", "keywords": ["drainage", "road", "flooding"], "location_hint": "main road", "demand_count_hint": "commuters"},
    {"original_text": "Borewell installed last year is now giving contaminated water with high fluoride. Children in our village have dental and bone problems. 120 households affected.", "translated_text": "Borewell installed last year is now giving contaminated water with high fluoride. Children in our village have dental and bone problems. 120 households affected.", "source_language": "en", "constituency": "Demo Constituency", "district": "", "lat": 16.1567, "lng": 80.0345, "input_type": "text", "theme": "Water Supply", "summary": "Fluoride contamination in borewell, children have bone/dental problems", "urgency": "High", "sentiment": "Negative", "keywords": ["fluoride", "borewell", "contamination", "children"], "location_hint": "village borewell", "demand_count_hint": "120 households"},
    {"original_text": "हमारे गाँव में पानी की टंकी 6 महीने पहले टूट गई। अभी तक मरम्मत नहीं हुई। महिलाएं 3 किलोमीटर दूर से पानी लाती हैं।", "translated_text": "The water tank in our village broke 6 months ago. No repair done yet. Women walk 3 km to fetch water.", "source_language": "hi", "constituency": "Demo Constituency", "district": "", "lat": 16.2789, "lng": 80.0612, "input_type": "text", "theme": "Water Supply", "summary": "Water tank broken 6 months, women walk 3km to fetch water", "urgency": "High", "sentiment": "Negative", "keywords": ["water tank", "women", "3km", "repair"], "location_hint": "village water tank", "demand_count_hint": "village women"},
    {"original_text": "Water pipeline is leaking at 4 points on the main road. Wasting thousands of litres daily. Road also getting damaged due to waterlogging.", "translated_text": "Water pipeline is leaking at 4 points on the main road. Wasting thousands of litres daily. Road also getting damaged due to waterlogging.", "source_language": "en", "constituency": "Demo Constituency", "district": "", "lat": 16.2412, "lng": 80.1234, "input_type": "text", "theme": "Water Supply", "summary": "Pipeline leaking at 4 points, thousands of litres wasted daily", "urgency": "Medium", "sentiment": "Negative", "keywords": ["pipeline", "leaking", "water waste", "road damage"], "location_hint": "main road pipeline", "demand_count_hint": "all residents"},
    {"original_text": "Open canal water is being used for drinking in Thullur mandal because taps run dry. Risk of cholera outbreak. Children are falling sick frequently.", "translated_text": "Open canal water is being used for drinking in Thullur mandal because taps run dry. Risk of cholera outbreak. Children are falling sick frequently.", "source_language": "en", "constituency": "Demo Constituency", "district": "", "lat": 16.3123, "lng": 80.2345, "input_type": "text", "theme": "Water Supply", "summary": "Canal water consumed for drinking, cholera risk, children falling ill", "urgency": "High", "sentiment": "Negative", "keywords": ["canal water", "drinking", "cholera", "children sick"], "location_hint": "Thullur mandal", "demand_count_hint": "mandal residents"},
    {"original_text": "Primary Health Centre in our mandal has no doctor since 6 months. Only an ANM is present. Pregnant women have to travel 25 km to district hospital.", "translated_text": "Primary Health Centre in our mandal has no doctor since 6 months. Only an ANM is present. Pregnant women have to travel 25 km to district hospital.", "source_language": "en", "constituency": "Demo Constituency", "district": "", "lat": 16.1987, "lng": 79.9876, "input_type": "text", "theme": "Healthcare & Sanitation", "summary": "PHC has no doctor 6 months, pregnant women travel 25km", "urgency": "High", "sentiment": "Negative", "keywords": ["PHC", "doctor", "pregnant women", "hospital"], "location_hint": "mandal PHC", "demand_count_hint": "pregnant women, sick"},
    {"original_text": "Open defecation in our panchayat because 60% of households have no toilets. Swachh Bharat funds were sanctioned but work not started. Rainy season diseases are spreading.", "translated_text": "Open defecation in our panchayat because 60% of households have no toilets. Swachh Bharat funds were sanctioned but work not started. Rainy season diseases are spreading.", "source_language": "en", "constituency": "Demo Constituency", "district": "", "lat": 16.2678, "lng": 80.0987, "input_type": "text", "theme": "Healthcare & Sanitation", "summary": "60% no toilets, Swachh Bharat funds sanctioned but work not started", "urgency": "High", "sentiment": "Negative", "keywords": ["toilet", "Swachh Bharat", "open defecation", "disease"], "location_hint": "panchayat", "demand_count_hint": "60% of households"},
    {"original_text": "Garbage collected only once a week in our ward. Waste is piling up near the school. Children are falling ill due to stench and flies. Need daily collection.", "translated_text": "Garbage collected only once a week in our ward. Waste is piling up near the school. Children are falling ill due to stench and flies. Need daily collection.", "source_language": "en", "constituency": "Demo Constituency", "district": "", "lat": 16.2156, "lng": 80.1456, "input_type": "text", "theme": "Healthcare & Sanitation", "summary": "Weekly garbage collection insufficient, waste near school, children ill", "urgency": "Medium", "sentiment": "Negative", "keywords": ["garbage", "waste", "school", "children sick"], "location_hint": "ward near school", "demand_count_hint": "ward residents"},
    {"original_text": "Government school has 380 students but only 4 teachers. Classes 6, 7, 8 have no subject teachers — one teacher takes all subjects. Quality of learning is very poor.", "translated_text": "Government school has 380 students but only 4 teachers. Classes 6, 7, 8 have no subject teachers — one teacher takes all subjects. Quality of learning is very poor.", "source_language": "en", "constituency": "Demo Constituency", "district": "", "lat": 16.2034, "lng": 80.1345, "input_type": "text", "theme": "Education", "summary": "380 students, only 4 teachers, classes 6-8 lack subject teachers", "urgency": "High", "sentiment": "Negative", "keywords": ["school", "teachers", "students", "education quality"], "location_hint": "government school", "demand_count_hint": "380 students"},
    {"original_text": "School has no functioning toilets for girls. This is the main reason girl students in classes 6-8 are dropping out. Toilet block needs urgent repair.", "translated_text": "School has no functioning toilets for girls. This is the main reason girl students in classes 6-8 are dropping out. Toilet block needs urgent repair.", "source_language": "en", "constituency": "Demo Constituency", "district": "", "lat": 16.1934, "lng": 80.0876, "input_type": "text", "theme": "Education", "summary": "No girl toilets in school causing dropout in classes 6-8", "urgency": "High", "sentiment": "Negative", "keywords": ["girls toilet", "dropout", "school", "repair"], "location_hint": "government school", "demand_count_hint": "girl students classes 6-8"},
    {"original_text": "No computer lab or internet in government school despite Digital India promises. 200 students in 9th and 10th cannot access online learning materials.", "translated_text": "No computer lab or internet in government school despite Digital India promises. 200 students in 9th and 10th cannot access online learning materials.", "source_language": "en", "constituency": "Demo Constituency", "district": "", "lat": 16.2512, "lng": 80.0712, "input_type": "text", "theme": "Education", "summary": "No computer lab despite Digital India, 200 students lack online access", "urgency": "Medium", "sentiment": "Negative", "keywords": ["computer lab", "internet", "Digital India", "students"], "location_hint": "government school", "demand_count_hint": "200 students"},
    {"original_text": "Power cuts of 8-10 hours daily during summer. Agricultural borewells cannot run. Crops are dying. Scheduled cuts are not followed — unscheduled outages are constant.", "translated_text": "Power cuts of 8-10 hours daily during summer. Agricultural borewells cannot run. Crops are dying. Scheduled cuts are not followed — unscheduled outages are constant.", "source_language": "en", "constituency": "Demo Constituency", "district": "", "lat": 16.3078, "lng": 80.0534, "input_type": "text", "theme": "Electricity", "summary": "8-10hr daily power cuts, borewells down, crops dying in summer", "urgency": "High", "sentiment": "Negative", "keywords": ["power cut", "borewell", "crops", "agriculture"], "location_hint": "agricultural area", "demand_count_hint": "farmers"},
    {"original_text": "Transformer serving 3 villages has been faulty for 2 months. APEPDCL keeps promising replacement but nothing has happened. 800 households affected.", "translated_text": "Transformer serving 3 villages has been faulty for 2 months. APEPDCL keeps promising replacement but nothing has happened. 800 households affected.", "source_language": "en", "constituency": "Demo Constituency", "district": "", "lat": 16.1678, "lng": 80.1789, "input_type": "text", "theme": "Electricity", "summary": "Faulty transformer 2 months, APEPDCL promises unfulfilled, 800 HH", "urgency": "High", "sentiment": "Negative", "keywords": ["transformer", "APEPDCL", "power", "households"], "location_hint": "3 villages", "demand_count_hint": "800 households"},
    {"original_text": "Canal sluice gates are broken and farmers cannot get water for rabi crops. The gates were supposed to be repaired under irrigation budget last year. 200 acres affected.", "translated_text": "Canal sluice gates are broken and farmers cannot get water for rabi crops. The gates were supposed to be repaired under irrigation budget last year. 200 acres affected.", "source_language": "en", "constituency": "Demo Constituency", "district": "", "lat": 16.2345, "lng": 79.9234, "input_type": "text", "theme": "Agriculture & Irrigation", "summary": "Canal sluice gates broken, no rabi water, 200 acres affected", "urgency": "High", "sentiment": "Negative", "keywords": ["canal", "sluice gate", "rabi", "irrigation"], "location_hint": "canal area", "demand_count_hint": "200 acres, farmers"},
    {"original_text": "किसान क्रेडिट कार्ड के लिए 4 बार बैंक गए लेकिन अधिकारी हर बार नए कागज़ात माँग रहे हैं। छोटे किसान साहूकारों से कर्ज़ ले रहे हैं।", "translated_text": "Went to bank 4 times for Kisan Credit Card but officers keep asking for new documents each time. Small farmers are taking loans from moneylenders.", "source_language": "hi", "constituency": "Demo Constituency", "district": "", "lat": 16.2812, "lng": 80.1056, "input_type": "text", "theme": "Agriculture & Irrigation", "summary": "KCC applications blocked by repeated document demands, farmers using moneylenders", "urgency": "High", "sentiment": "Negative", "keywords": ["Kisan Credit Card", "bank", "farmers", "moneylenders"], "location_hint": "bank", "demand_count_hint": "small farmers"},
    {"original_text": "Cold storage facility promised 3 years ago never built. Farmers lose 30% of their tomato and onion produce due to lack of storage. Urgently needed.", "translated_text": "Cold storage facility promised 3 years ago never built. Farmers lose 30% of their tomato and onion produce due to lack of storage. Urgently needed.", "source_language": "en", "constituency": "Demo Constituency", "district": "", "lat": 16.1456, "lng": 80.0123, "input_type": "text", "theme": "Agriculture & Irrigation", "summary": "Cold storage promised 3 years ago not built, 30% produce lost", "urgency": "High", "sentiment": "Negative", "keywords": ["cold storage", "tomato", "onion", "farmers"], "location_hint": "farming area", "demand_count_hint": "all vegetable farmers"},
    {"original_text": "PMAY housing list was prepared 2 years ago but houses not constructed. Beneficiaries received first installment but contractor abandoned work after foundation.", "translated_text": "PMAY housing list was prepared 2 years ago but houses not constructed. Beneficiaries received first installment but contractor abandoned work after foundation.", "source_language": "en", "constituency": "Demo Constituency", "district": "", "lat": 16.2234, "lng": 80.1567, "input_type": "text", "theme": "Housing & Land", "summary": "PMAY houses not built 2 years, contractor abandoned after foundation", "urgency": "High", "sentiment": "Negative", "keywords": ["PMAY", "housing", "contractor", "abandoned"], "location_hint": "PMAY site", "demand_count_hint": "PMAY beneficiaries"},
    {"original_text": "MGNREGS work in our panchayat has stopped for 3 months. Job cards are active but no work orders issued. Labourers are going to cities for daily wage work.", "translated_text": "MGNREGS work in our panchayat has stopped for 3 months. Job cards are active but no work orders issued. Labourers are going to cities for daily wage work.", "source_language": "en", "constituency": "Demo Constituency", "district": "", "lat": 16.2667, "lng": 80.0789, "input_type": "text", "theme": "Employment & Livelihood", "summary": "MGNREGS stopped 3 months, labourers migrating to cities", "urgency": "High", "sentiment": "Negative", "keywords": ["MGNREGS", "job cards", "labourers", "migration"], "location_hint": "panchayat", "demand_count_hint": "labourers"},
    {"original_text": "Youth in our area are highly educated but unemployed. Skill development centre building is constructed but never opened. 500 youth waiting for vocational training.", "translated_text": "Youth in our area are highly educated but unemployed. Skill development centre building is constructed but never opened. 500 youth waiting for vocational training.", "source_language": "en", "constituency": "Demo Constituency", "district": "", "lat": 16.2089, "lng": 80.1234, "input_type": "text", "theme": "Employment & Livelihood", "summary": "Skill centre built but never opened, 500 youth unemployed waiting", "urgency": "Medium", "sentiment": "Negative", "keywords": ["skill centre", "youth", "unemployment", "vocational"], "location_hint": "skill development centre", "demand_count_hint": "500 youth"},
    {"original_text": "No police outpost in our panchayat cluster of 8 villages. Nearest police station is 18 km away. Petty thefts and eve-teasing incidents increasing. Women feel unsafe.", "translated_text": "No police outpost in our panchayat cluster of 8 villages. Nearest police station is 18 km away. Petty thefts and eve-teasing incidents increasing. Women feel unsafe.", "source_language": "en", "constituency": "Demo Constituency", "district": "", "lat": 16.3234, "lng": 80.0456, "input_type": "text", "theme": "Law & Order", "summary": "No police in 8 villages, 18km to station, thefts and eve-teasing rising", "urgency": "High", "sentiment": "Negative", "keywords": ["police", "safety", "theft", "women"], "location_hint": "8 panchayat villages", "demand_count_hint": "8 villages"},
    {"original_text": "Illegal factory dumping chemical waste into the local lake. Fish have died. Drinking water from borewells smells of chemicals. Kids have skin rashes.", "translated_text": "Illegal factory dumping chemical waste into the local lake. Fish have died. Drinking water from borewells smells of chemicals. Kids have skin rashes.", "source_language": "en", "constituency": "Demo Constituency", "district": "", "lat": 16.1789, "lng": 80.2123, "input_type": "text", "theme": "Environment & Waste", "summary": "Factory dumping chemicals in lake, fish dead, borewell water contaminated", "urgency": "High", "sentiment": "Negative", "keywords": ["chemical waste", "lake", "pollution", "children sick"], "location_hint": "local lake", "demand_count_hint": "lakeside village"},
    {"original_text": "Plastic waste burning near residential area every evening. CPCB norms are being violated. Children have respiratory problems. Local body is ignoring complaints.", "translated_text": "Plastic waste burning near residential area every evening. CPCB norms are being violated. Children have respiratory problems. Local body is ignoring complaints.", "source_language": "en", "constituency": "Demo Constituency", "district": "", "lat": 16.2345, "lng": 80.1678, "input_type": "text", "theme": "Environment & Waste", "summary": "Plastic burning daily near homes, CPCB violation, children have breathing problems", "urgency": "High", "sentiment": "Negative", "keywords": ["plastic burning", "CPCB", "pollution", "respiratory"], "location_hint": "residential area", "demand_count_hint": "residential colony"},
]


def _verify_admin(x_admin_secret: str = Header(default="")):
    secret = os.environ.get("ADMIN_SECRET", "")
    # If no secret configured, allow (dev mode). Otherwise verify.
    if secret and x_admin_secret != secret:
        raise HTTPException(status_code=403, detail="Invalid admin secret")


@router.post("/seed")
def seed_data(x_admin_secret: str = Header(default="")):
    """Insert pre-computed seed submissions directly — no Gemini call."""
    if os.environ.get("ENABLE_ADMIN", "false").lower() != "true":
        raise HTTPException(status_code=404, detail="Not found")
    _verify_admin(x_admin_secret)

    from datetime import datetime, timezone
    inserted = 0
    for sub in SEED_DATA:
        try:
            sub["created_at"] = datetime.now(timezone.utc).isoformat()
            firestore_service.save_submission(sub)
            inserted += 1
        except Exception as e:
            pass

    return {"seeded": inserted, "total": len(SEED_DATA), "status": "ok"}


@router.delete("/reset")
def reset_data(x_admin_secret: str = Header(default="")):
    """Wipe all submissions (SQLite only — dev use)."""
    if os.environ.get("ENABLE_ADMIN", "false").lower() != "true":
        raise HTTPException(status_code=404, detail="Not found")
    _verify_admin(x_admin_secret)

    import os as _os
    from services.sqlite_service import _conn
    con = _conn()
    con.execute("DELETE FROM submissions")
    con.commit()
    con.close()
    return {"status": "reset", "message": "All submissions deleted"}
